//JSON data array
var artists = [
	{title: "Lecrae", 
	className: "tableRow", 
	hasChild: true,
	artistImage: "Images/LECRAE.png", 
	album: "Album: Church Clothes 2", 
	artist: "Artist: Lecrae", 
	releaseDate: "Released: Nov 08, 2013",
	record: "Label: Reach Records", 
	avgRating: "Average Rating: 5 out of 5",
	genres: "Genres: Hip-Hop " +  "Rap " + "Christian Rap",
	band: "Band Members: Lecrae" 
	},
	
	{title: "Derek Minor", 
	className: "tableRow", 
	hasChild: true,
	artistImage: "Images/MINOR.png", 
	album: "Album: Minorville", 
	artist: "Derek Minor", 
	releaseDate: "Released: April 09, 2014",
	record: "Label: Reach Records", 
	avgRating: "Average Rating: 5 out of 5",
	genres: "Genres: Hip-Hop, Rap",
	band: "Band Members: Derek Minor"
	},
	
	{title: "The Fray", 
	className: "tableRow", 
	hasChild: true,
	artistImage: "Images/FRAY.png", 
	album: "Album: Helios", 
	artist: "The Fray", 
	releaseDate: "Released: Jan 14, 2014",
	record: "Label: Epic Records", 
	avgRating: "Average Rating: 4 out of 5",
	genres: "Genres: Pop",
	band: "Band Members: Isaac Slade " + "Joe King " +  "Dave Welsh " + "& Ben Wysocki"
	},
	
	{title: "Switchfoot", 
	className: "tableRow", 
	hasChild: true,
	artistImage: "Images/SWITCHFOOT.png", 
	album: "Album: Fading West", 
	artist: "Switchfoot", 
	releaseDate: "Released: Jan 10, 2014",
	record: "Label: Atlantic Recording Corp.", 
	avgRating: "Average Rating: 4.5 out of 5",
	genres: "Genres: Pop",
	band: "Band Members: Jon Foreman " + "Tim Foreman " + "Chad Butler " + "Jerome Fontamillas " + "& Drew Shirley"},
	
	{title: "Red", 
	className: "tableRow", 
	hasChild: true,
	artistImage: "Images/Red.png", 
	album: "Album: Release The Panic", 
	artist: "Red", 
	releaseDate: "Released: Feb 01, 2013",
	record: "Label: Provident Label Group LLC", 
	avgRating: "Average Rating: 4.5 out of 5",
	genres: "Genres: Rock, Music, Metal,Christian Rock.",
	band: "Band Members: Lecrae"},
	
	{title: "Tedashii", 
	className: "tableRow", 
	hasChild: true,
	artistImage: "Images/LECRAE.png", 
	album: "Album: Church Clothes 2", 
	artist: "Lecrae", 
	releaseDate: "Released: Nov 08, 2013",
	record: "Label: Reach Records", 
	avgRating: "Average Rating: 5 out of 5",
	genres: "Genres: Hip-Hop, Rap, Music, Christian & Gospel, Christian Rap, Rap, Gospel",
	band: "Band Members: Lecrae"},
	
	{title: "Trip Lee", 
	className: "tableRow", 
	hasChild: true,
	artistImage: "Images/LECRAE.png", 
	album: "Album: Church Clothes 2", 
	artist: "Lecrae", 
	releaseDate: "Released: Nov 08, 2013",
	record: "Label: Reach Records", 
	avgRating: "Average Rating: 5 out of 5",
	genres: "Genres: Hip-Hop, Rap, Music, Christian & Gospel, Christian Rap, Rap, Gospel",
	band: "Band Members: Lecrae"},
	
	{title: "Andy Mineo", 
	className: "tableRow", 
	hasChild: true,
	artistImage: "Images/LECRAE.png", 
	album: "Album: Church Clothes 2", 
	artist: "Lecrae", 
	releaseDate: "Released: Nov 08, 2013",
	record: "Label: Reach Records", 
	avgRating: "Average Rating: 5 out of 5",
	genres: "Genres: Hip-Hop, Rap, Music, Christian & Gospel, Christian Rap, Rap, Gospel",
	band: "Band Members: Lecrae"},
	
	{title: "Lifehouse", 
	className: "tableRow", 
	hasChild: true,
	artistImage: "Images/LECRAE.png", 
	album: "Album: Church Clothes 2", 
	artist: "Lecrae", 
	releaseDate: "Released: Nov 08, 2013",
	record: "Label: Reach Records", 
	avgRating: "Average Rating: 5 out of 5",
	genres: "Genres: Hip-Hop, Rap, Music, Christian & Gospel, Christian Rap, Rap, Gospel",
	band: "Band Members: Lecrae"},
	
	{title: "Paper Tongues", 
	className: "tableRow", 
	hasChild: true,
	artistImage: "Images/LECRAE.png", 
	album: "Album: Church Clothes 2", 
	artist: "Lecrae", 
	releaseDate: "Released: Nov 08, 2013",
	record: "Label: Reach Records", 
	avgRating: "Average Rating: 5 out of 5",
	genres: "Genres: Hip-Hop, Rap, Music, Christian & Gospel, Christian Rap, Rap, Gospel",
	band: "Band Members: Lecrae"}
];